// Shared Krankenkassen options for all verticals
export const krankenkassenOptions = [
  { value: "AOK", label: "AOK" },
  { value: "AOK Baden-Württemberg", label: "AOK Baden-Württemberg" },
  { value: "AOK Bayern", label: "AOK Bayern" },
  { value: "AOK Bremen/Bremerhaven", label: "AOK Bremen/Bremerhaven" },
  { value: "AOK Hessen", label: "AOK Hessen" },
  { value: "AOK Niedersachsen", label: "AOK Niedersachsen" },
  { value: "AOK Nordost", label: "AOK Nordost" },
  { value: "AOK Nordwest", label: "AOK Nordwest" },
  { value: "AOK PLUS", label: "AOK PLUS" },
  { value: "AOK Rheinland-Pfalz/Saarland", label: "AOK Rheinland-Pfalz/Saarland" },
  { value: "AOK Rheinland/Hamburg", label: "AOK Rheinland/Hamburg" },
  { value: "AOK Sachsen-Anhalt", label: "AOK Sachsen-Anhalt" },
  { value: "Barmer", label: "Barmer" },
  { value: "Techniker Krankenkasse (TK)", label: "Techniker Krankenkasse (TK)" },
  { value: "DAK-Gesundheit", label: "DAK-Gesundheit" },
  { value: "IKK classic", label: "IKK classic" },
  { value: "IKK gesund plus", label: "IKK gesund plus" },
  { value: "IKK Südwest", label: "IKK Südwest" },
  { value: "IKK Brandenburg und Berlin", label: "IKK Brandenburg und Berlin" },
  { value: "IKK Nord", label: "IKK Nord" },
  { value: "KKH Kaufmännische Krankenkasse", label: "KKH Kaufmännische Krankenkasse" },
  { value: "hkk", label: "hkk" },
  { value: "HEK - Hanseatische Krankenkasse", label: "HEK - Hanseatische Krankenkasse" },
  { value: "Knappschaft", label: "Knappschaft" },
  { value: "BIG direkt gesund", label: "BIG direkt gesund" },
  { value: "Mobil Krankenkasse", label: "Mobil Krankenkasse" },
  { value: "BKK", label: "BKK (Betriebskrankenkasse)" },
  { value: "BKK Mobil Oil", label: "BKK Mobil Oil" },
  { value: "BKK VBU", label: "BKK VBU" },
  { value: "BKK Linde", label: "BKK Linde" },
  { value: "BKK ProVita", label: "BKK ProVita" },
  { value: "BKK firmus", label: "BKK firmus" },
  { value: "BKK Wirtschaft & Finanzen", label: "BKK Wirtschaft & Finanzen" },
  { value: "Bertelsmann BKK", label: "Bertelsmann BKK" },
  { value: "Debeka BKK", label: "Debeka BKK" },
  { value: "Novitas BKK", label: "Novitas BKK" },
  { value: "Pronova BKK", label: "Pronova BKK" },
  { value: "Salus BKK", label: "Salus BKK" },
  { value: "SBK Siemens-Betriebskrankenkasse", label: "SBK Siemens-Betriebskrankenkasse" },
  { value: "Viactiv Krankenkasse", label: "Viactiv Krankenkasse" },
  { value: "Vivida BKK", label: "Vivida BKK" },
  { value: "Heimat Krankenkasse", label: "Heimat Krankenkasse" },
  { value: "mhplus Krankenkasse", label: "mhplus Krankenkasse" },
  { value: "Audi BKK", label: "Audi BKK" },
  { value: "BMW BKK", label: "BMW BKK" },
  { value: "Bosch BKK", label: "Bosch BKK" },
  { value: "Continentale BKK", label: "Continentale BKK" },
  { value: "Daimler BKK", label: "Daimler BKK" },
  { value: "energie-BKK", label: "energie-BKK" },
  { value: "Metzinger BKK", label: "Metzinger BKK" },
  { value: "R+V Betriebskrankenkasse", label: "R+V Betriebskrankenkasse" },
  { value: "SKD BKK", label: "SKD BKK" },
  { value: "TUI BKK", label: "TUI BKK" },
  { value: "WMF BKK", label: "WMF BKK" },
  { value: "Die Schwenninger Krankenkasse", label: "Die Schwenninger Krankenkasse" },
  { value: "SVLFG", label: "SVLFG" },
  { value: "Privat versichert", label: "Privat versichert" },
  { value: "Sonstige", label: "Sonstige" },
]

// Simple string list for components that need it (e.g., pflegebox combobox)
export const krankenkassenList = krankenkassenOptions.map((option) => option.label)
